### ISSUE TITLE
[bug] fastify missing in peerDep

### ISSUE THREAD

**Issue by onichandame** [fastify/middie#100]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.20.2 

### Node.js version

v15.10.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

3.13.5

#### Problem

This lib requires `fastify` as a direct dependency but does not declare it in either `dependencies` or `peerDependencies`. This is not a problem in most cases if not using yarn v2, but it panics when yarn v2 forbids access to dependencies other than those explicitly declared in `package.json`.

This bug can also lead to errors if the installed version of `fastify` is not compatible with this lib.

#### Solution

Add `fastify` to peerDep with reasonable version requirement (e.g. ^3.0.0)

### Steps to Reproduce

See description.

**Comment by Eomm** [comment]
In these duplicates, you can find the workaround:

https://github.com/fastify/fastify-swagger/issues/220
https://github.com/fastify/fastify-static/issues/159

The [decision](https://github.com/fastify/fastify-swagger/issues/220#issuecomment-583280362) has been to don't add it as `peerDependencies`.

Since npm v7 has been released, we should re-evaluate it: would you like to analyze if it is doable?

**Comment by onichandame** [comment]
Thx for the links. I have patched middie's peerDeps in .yarnrc.yml as a workaround and it just works. I do agree that npm with peerDeps is a nightmare so adding fastify into peerDeps may break some consumers who are using npm.

Unfortunately, I have no idea how npm 7 is different from the previous npm. I'd like to play around with it but can't say when I will come to a solid conclusion.

**Comment by jsumners** [comment]
I think the only problem is documentation. It _should_ be clear that this module is useless without a parent Fastify application, but it seems some people think it is wholly self-sufficient. The documentation should be clear that you need a parent Fastify application, which would mean `npm i --save fastify` has been done.

**Comment by onichandame** [comment]
not just documentation really. In yarn v2 Plug'n'Play mode, a package can only access other packages if they are declared in its `dependencies` or `peerDependences` section.

```text
package 1 ->(depends on)-> package 2
```

In this case, the package.json of package 1 must-have package 2 included in either `dependencies` or `peerDependencies`.

```text
app ->(depends on)-> package 1 ->(depends on)-> package 2
```

In this case still the package.json of package 1 must-have package 2 declared in deps or peerDeps. Even if package 2 is installed directly in the app, package 1 would not be able to utilize that.

**Comment by jsumners** [comment]
When you use a non-standard package manager then it is your responsibility to deal with the idiosyncrasies. I don't care how many people use Yarn or PNPM or whatever. The standard package manager is npm as shipped with the cuurent LTS release of Node core.

**Comment by onichandame** [comment]
Should I take the claim that "yarn is not supported" as an official announcement from the fastify team? If so, I think there is nothing more we can do here and the issue can be closed. Please clarify it, thanks

**Comment by Eomm** [comment]
> Should I take the claim that "yarn is not supported" as an official announcement from the fastify team?

No, we have the CI pipeline in place too.
We must support `npm` too, and it has the larger adoption.

`yarn` works as well, but some plugins require the `packageExtensions` extra configuration.
I think that this issue can be addressed by adding a `## Working with yarn` section in the readme that explains what needs to be done to let yarn works as expected.

I think you may propose the `yarn` team to read, from a module's package.json an extra field:

```
yarn: {
   packageExtensions: {} // ...
}
```

so we could ship the configuration by default and you would no need to edit your `yarnrc` file.
