### ISSUE TITLE
Throw error when middleware callback is not called after certain amount of time

### ISSUE THREAD

**Issue by StarpTech** [fastify/middie#11]
This can be easy implemented with `setTimeout` e.g with a timeout of `5000`. It's useful because when you have lots of middleware it's hard to find the root issue.

**Comment by mcollina** [comment]
Very nice question. I'm -1 on this approach for two reasons:

a) timers are slow
b) stopping a request in this way does not release whatever resources are allocated to process it.

In practice a generic approach does not work and it creates a lot of overhead. If you have these types of concerns on some routes, you should implement time checks when a callback gets back to you.

**Comment by StarpTech** [comment]
a) This is only for the init process for the server. The timers are recycled asap.
b) What's when the error is thrown asynchronously? At some time in the future 3-6 seconds?

**Comment by StarpTech** [comment]
Middie could throw a meaningful error e.g based on a context property, function name...

**Comment by mcollina** [comment]
> a) This is only for the init process of the server. The timers are recycled asap.

I might not have understood what you are proposing then. It seems you are proposing to allocate a timer for every middleware call for every incoming request.

> b) What's when the error is thrown asynchronously? At some time in the future 3-6 seconds when the callback was not fired.

can you make an example in code?

I would like to keep this as similar to express as possible, and express does not have a timer for every middleware call.

**Comment by StarpTech** [comment]
Ok my bad, I'm talking about fastify plugin registration. I don't mean to use in the middleware.

**Comment by mcollina** [comment]
Oh! open an issue in the main repo then! Can you attach an example in code?
