### ISSUE TITLE
Routes using middie middleware inside fastify plugin do not get registered

### ISSUE THREAD

**Issue by BenjaVR** [fastify/middie#111]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.0

### Plugin version

5.3.0

### Node.js version

14.18.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

If you define middleware with a route inside a fastify plugin, the route will not resolve and result in a 404 error.

### Steps to Reproduce

You can find a fully working example in this Codesandbox: https://codesandbox.io/s/middie-middleware-inside-fastify-plugin-9nt6e

These are the minimal steps you have to follow:

1. Register the middie plugin.
    ```js
    await fastify.register(middiePlugin);
    ```

2. Create another js file with a custom plugin that only registers a certain middleware with a path
    ```js
    await fastify.use("/demo", (_req, res) => {
      res.write("demo plugin");
      res.end();
    });
    ```

3. Use the middleware in your main js file with a path prefix
    ```js
    await fastify.register(plugin, { prefix: "plugin" });
    ```

4. Try to navigate to `/plugin/demo`, this will result in a 404.

### Expected Behavior

In the example, when you go to `/plugin/demo`, you should see `demo plugin` with status code 200 as result, instead we get a 404.

All the other routes in the example do resolve correctly.

**Comment by mcollina** [comment]
That's because the radix prefix trie does not know anything about the `/plugin/demo` middleware.

You'd need to add a Fastify route inside your `plugin.js` for this to match,

**Comment by BenjaVR** [comment]
If I understand it correctly, I have to do something like this (in my plugin file):

```js
await fastify.use("/demo", (_req, res) => {
  res.write("demo plugin");
  res.end();
});
// Dummy route registration to make sure the middleware with same route gets registered.
await fastify.all("/demo", async () => {
  return;
});
```

Here is an updated CSB with 2 plugins, each defining middleware with the same routes. Everything seems to work fine here: https://codesandbox.io/s/middie-middleware-inside-fastify-plugin-fix-example-multiple-plugins-be9q0

However, if I have another middleware with the `/demo` route (`/demo`) in my main application, it will override the response of the one in my plugin (`/plugin/demo`). But since this is middleware and not 'just' a route, I think this is expected behavior? If so, this issue can be closed, thanks! 👌

**Comment by mcollina** [comment]
Exactly!
