### ISSUE TITLE
Middleware executed on subroutes

### ISSUE THREAD

**Issue by MatthiasKunnen** [fastify/middie#113]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.23.0

### Plugin version

5.3.0

### Node.js version

16.13.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 18.04

### Description

The current configuration used for [`pathToRegexp`](https://www.npmjs.com/package/path-to-regexp) causes subroutes to be matched.

Current configuration:
https://github.com/fastify/middie/blob/33065d3ec0b7a82ef48a7ce5cb52e2296913ce82/engine.js#L23-L26

I'm running into this issue when using Nestjs + Fastify where a controller has middleware applied (using `.apply(RootMiddleware).forRoutes(RootController)`) and defines a method with one of the following: `@Get()`, `@Get('/')`, or `@Get('')`.  Requesting any route not defined in the `RootController` will cause the `RootMiddleware` to be executed.

### Steps to Reproduce

1. Register middleware on `/`
2. Request `/contact`
3. The middleware will execute

### Expected Behavior

The middleware registered to '/' should execute on:
- `/`
- `/?hello`
- `/#hello`
- `/?hello#hello`

but **not** execute on:
- `/test`
- `/contact`

**Comment by Eomm** [comment]
Not sure if it is a nestjs issue, since it is the one that manages how this plugin is used.

Would you like to check it deeper?

**Comment by MatthiasKunnen** [comment]
What would you like me to do? Make a nestjs reproduction? Or a middie only
one? Or something else entirely?

I debugged this issue in my application until I traced it to middie.

**Comment by MatthiasKunnen** [comment]
I created a test case here: https://github.com/MatthiasKunnen/middie/tree/middleware-executed-on-subroutes

https://github.com/MatthiasKunnen/middie/blob/f43e2c6e98dd2115d8057f6c3b5c5f1fe1c54c92/test/basic.test.js#L134-L161

**Comment by mcollina** [comment]
I think the current behavior is correct. It uses prefix-matching, so all routes matching that prefix will execute the middleware. Using / would make sure it is executed in all routes.

I would recommend you to stop using middlewares and use lifecycle hooks instead.
