### ISSUE TITLE
Not working without await

### ISSUE THREAD

**Issue by polRk** [fastify/middie#169]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.0

### Plugin version

8.0.0

### Node.js version

19

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

```ts
import Fastify from "fastify";
import FastifyMiddie from "@fastify/middie";
```

NOT Working
```ts
  const app = Fastify();
  app.register(FastifyMiddie);

  app.use() // .use - undefined
```

Working
```ts
  const app = Fastify();
  await app.register(FastifyMiddie);

  app.use()
```

### Steps to Reproduce

```
import Fastify from "fastify";
import FastifyMiddie from "@fastify/middie";

const app = Fastify();
await app.register(FastifyMiddie);

app.use()
```
  

### Expected Behavior

plugin and .use available

**Comment by Uzlopak** [comment]
You have to await register as register is async.

Works as expected.
