### ISSUE TITLE
Middie doesn't accept generics

### ISSUE THREAD

**Issue by Igorgro** [fastify/middie#175]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

While I can use type generics in regular fastify like this:
```typescript
fastify.get<{ Querystring: { id: number } }>('/', async (req , rep) => {
...
});
```
I cannot add type generics to use function. This code
```typescript
fastify.use<{ Querystring: { id: number } }>('/', async (req, rep, next) => {
...
})
```
doesn't compile with the following error: `TS2558: Expected 0 type arguments, but got 1`. I think that `use` function should accept the same type aurguments as the fastify `get`, `post` functions.

**Comment by Eomm** [comment]
> `fastify.use<{ Querystring: { id: number } }>('/', async (req, rep, next) => {`

you can't use the `next` arg with an `async` function
