### ISSUE TITLE
literally everyone will read the name of this package as `middle`

### ISSUE THREAD

**Issue by ExProbitasFiducia** [fastify/middie#182]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

>3

### Node.js version

any

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

any

### Description

i mean really the first interaction is gonna be "the package cant be found" and will leave people annoyed.

Make it loud and clear that the name of the package is with an I as in Icicle or make a `middle` package with a postinstall hook that's super loud "THIS IS THE WRONG PACKAGE< YOU PROBABLY MEANT MIDDIE` or something please...

### Steps to Reproduce

`yarn add @fastify/middle`

**Comment by b1ek** [comment]
I agree, that's a fair point. Why is it closed as not planned?
