### ISSUE TITLE
Add exports field, for @fastify/middie/engine

### ISSUE THREAD

**Issue by wobsoriano** [fastify/middie#186]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'm unable to use the `/engine` in projects using ESM and throws this error:

```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/fastify-next-auth/node_modules/@fastify/middie/engine' imported from //tmp/fastify-next-auth/dist/index.mjs
```

I made it work when I manually changed `@fastify/middie` `package.json` by adding exports field:

```json
"exports": {
  ".": {
    "require": "./index.js"
  },
  "./engine": {
    "require": "./lib/engine.js",
    "import": "./lib/engine.js"
  }
},
```

Would you accept a PR or do you have a better solution? Thank you!

### Motivation

Authored

- https://github.com/wobsoriano/fastify-next-auth
- https://github.com/wobsoriano/authey

### Example

```ts
import Middie from '@fastify/middie/engine'
```

_No response_

**Comment by Eomm** [comment]
Is the application bundled?

**Comment by wobsoriano** [comment]
Do you mean https://github.com/wobsoriano/fastify-next-auth? It is bundled. For now, I copied the contents of the [engine](https://github.com/wobsoriano/fastify-next-auth/blob/master/src/middie.js) and added credits to it.
