### ISSUE TITLE
Add option to pass full fastify request/reply to middleware

### ISSUE THREAD

**Issue by BlakeB415** [fastify/middie#188]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Some applications would like access to the full fastify request object in middleware. Unfortunately, middie only sends the raw request object.

I propose that an **optional** parameter be added to change this behavior. The property would tell middie to pass the full fastify request/reply object instead.

This should be non-breaking as it only affects people who enable it.

### Motivation

I'm using NestJS with the fastify module and it's not ideal having to do .raw on everything to get values set in middleware.

For a few months now I've been using a patch I wrote to pass it through to the middleware. However, this isn't a permanent solution. 

### Example

Something like
```
fastify.register(require('@fastify/middie'), { fullRequest: true })
```

**Comment by Eomm** [comment]
Not sure why you should use `@fastify/middie` in this case if you can use hooks  - this plugin was designed to support express users to migrate to fastify.

So, using middie with fastify's objects would mean you may use fastify's hooks directly.

Did you try it?

**Comment by BlakeB415** [comment]
> Not sure why you should use `@fastify/middie` in this case if you can use hooks - this plugin was designed to support express users to migrate to fastify.
> 
> So, using middie with fastify's objects would mean you may use fastify's hooks directly.
> 
> Did you try it?

We’re using NestJS (which uses middie with fastify) so we don’t really have control over that directly. I believe the reason they used it is due to the middleware chaining as that doesn’t seem to be possible with Fastify.

Whether this is something that should be done in NestJS or Middie I have no idea. I’ll open up an issue on NestJS tomorrow.

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](https://discord.gg/NestJS) channel (support) for such questions.
