### ISSUE TITLE
Error: fastify-plugin: middie - expected '>=3.0.0' fastify version, '2.14.1' is installed

### ISSUE THREAD

**Issue by jaganathanb** [fastify/middie#43]
## 🐛 Bug Report

`fastify-plugin` errors out as `middie` demands `fastify` version >=3.0.0 but the latest version is 2.14.1.

## To Reproduce

Install fastify and middie.
Run the sample server code with middie usage.
## Expected behavior
Fastify plugin should not report to install the version 3.0.0 which is not release yet. Looks like, it is in rc3 version.

Middie either should demand the rc3  version or demand the 2.14.1. 

## Your Environment

- *node version*: 12
- *fastify version*: >=2.14.1
- *os*: Windows

**Comment by mcollina** [comment]
```
npm install fastify@next
```

This will install 3.0.0-rc.3, which will work.
