### ISSUE TITLE
Routes format limitations

### ISSUE THREAD

**Issue by giovanniRodighiero** [fastify/middie#5]
Hi guys, I really like the Fastify project and I hope to find the time to try it out more in depth.

Anyway I was playing with it writing some middlewares and I was wondering if the routes format limitations (like `/users/:id`) are due to the dependency with [pathname-match](https://github.com/yoshuawuyts/pathname-match) which basically just strips away query params and anchors. 

Would you consider replacing it with something more complex (probably), but yet more powerful and flexible like [route-parser](https://github.com/rcs/route-parser), in order to allow more complex routes configuration on a single middleware ?

I can gladly work on a PR about this in my spare time if you like this idea.

**Comment by delvedor** [comment]
Actually for the routing we are using [find-my-way](https://github.com/delvedor/find-my-way), pathname-match is used just for strip the url (which is the [scope](https://github.com/yoshuawuyts/pathname-match#why) of the module), probably we should use the same [approach](https://github.com/delvedor/find-my-way/blob/master/index.js#L136-L137) we adopted in find-my-way, which is faster.

In any case the middlewares are executed before the routing, so rules like `'/user/:id'` will not work at all. Probably what you need is the `preHandler` hook, which gives you the exact request with the parsed parameters. Have a look [here](https://github.com/fastify/fastify/blob/master/docs/Hooks.md)!

**Comment by delvedor** [comment]
Closing this, if you have more questions please let me know! We are also on [gitter](gitter.im/fastify) :)
